"""Seed trust-transition cause codes used by the executable reference layer."""

from __future__ import annotations

TRUST_CAUSE_SOURCE_UNAVAILABLE = "TRUST_CAUSE_SOURCE_UNAVAILABLE"
TRUST_CAUSE_DATA_STALE = "TRUST_CAUSE_DATA_STALE"
TRUST_CAUSE_TIMING_INVALID = "TRUST_CAUSE_TIMING_INVALID"
TRUST_CAUSE_VALUE_IMPLAUSIBLE = "TRUST_CAUSE_VALUE_IMPLAUSIBLE"
TRUST_CAUSE_SOURCE_DISAGREEMENT = "TRUST_CAUSE_SOURCE_DISAGREEMENT"
TRUST_CAUSE_NAV_CONTINUITY_BREAK = "TRUST_CAUSE_NAV_CONTINUITY_BREAK"
TRUST_CAUSE_NAV_SPOOF_SUSPECTED = "TRUST_CAUSE_NAV_SPOOF_SUSPECTED"
TRUST_CAUSE_INTEGRITY_FAILED = "TRUST_CAUSE_INTEGRITY_FAILED"
TRUST_CAUSE_RECOVERY_STEP = "TRUST_CAUSE_RECOVERY_STEP"
