"""Stable enum definitions shared across the IX-Style reference implementation."""

from __future__ import annotations

from enum import StrEnum


class MissionPhase(StrEnum):
    BOOTSTRAP = "BOOTSTRAP"
    READY = "READY"
    ACTIVE = "ACTIVE"
    CONTINGENCY = "CONTINGENCY"
    QUIESCENT = "QUIESCENT"


class SafetyPosture(StrEnum):
    INITIALIZING = "INITIALIZING"
    NOMINAL = "NOMINAL"
    SENSOR_DEGRADED = "SENSOR_DEGRADED"
    NAV_DEGRADED = "NAV_DEGRADED"
    COMMS_DEGRADED = "COMMS_DEGRADED"
    POWER_DEGRADED = "POWER_DEGRADED"
    ACTUATION_DEGRADED = "ACTUATION_DEGRADED"
    ASSURANCE_DEGRADED = "ASSURANCE_DEGRADED"
    SAFE_HOLD = "SAFE_HOLD"


class CommandSource(StrEnum):
    OPERATOR = "OPERATOR"
    MISSION_LOGIC = "MISSION_LOGIC"
    NOMINAL_AUTONOMY = "NOMINAL_AUTONOMY"
    CONTINGENCY_LOGIC = "CONTINGENCY_LOGIC"
    SAFETY_SUPERVISOR = "SAFETY_SUPERVISOR"
    NONE = "NONE"


class FunctionClass(StrEnum):
    MODE_MANAGEMENT = "MODE_MANAGEMENT"
    MISSION_INTENT = "MISSION_INTENT"
    GUIDANCE_REQUEST = "GUIDANCE_REQUEST"
    ACTUATION_REQUEST = "ACTUATION_REQUEST"
    RESOURCE_CONFIGURATION = "RESOURCE_CONFIGURATION"
    RECOVERY_ACTION = "RECOVERY_ACTION"
    POLICY_OVERRIDE = "POLICY_OVERRIDE"
    EVIDENCE_CONTROL = "EVIDENCE_CONTROL"


class ArbitrationOutcome(StrEnum):
    ACCEPT = "ACCEPT"
    REJECT = "REJECT"
    VETO = "VETO"
    CLAMP = "CLAMP"
    SUBSTITUTE = "SUBSTITUTE"
    DEFER = "DEFER"
    FREEZE = "FREEZE"
    ESCALATE_TO_MODE_CHANGE = "ESCALATE_TO_MODE_CHANGE"


class TrustDomain(StrEnum):
    SENSOR_SOURCE_TRUST = "SENSOR_SOURCE_TRUST"
    DERIVED_STATE_TRUST = "DERIVED_STATE_TRUST"
    NAVIGATION_TRUST = "NAVIGATION_TRUST"
    TIMING_TRUST = "TIMING_TRUST"
    MESSAGE_TRUST = "MESSAGE_TRUST"
    ACTUATOR_CONFIDENCE = "ACTUATOR_CONFIDENCE"
    ASSURANCE_CONFIDENCE = "ASSURANCE_CONFIDENCE"


class TrustState(StrEnum):
    TRUSTED = "TRUSTED"
    DEGRADED = "DEGRADED"
    SUSPECT = "SUSPECT"
    UNTRUSTED = "UNTRUSTED"
    UNAVAILABLE = "UNAVAILABLE"


class MessageClass(StrEnum):
    ADVISORY = "ADVISORY"
    CONTROL = "CONTROL"
    MODE_EVENT = "MODE_EVENT"
    TRUST_EVENT = "TRUST_EVENT"
    FAULT_EVENT = "FAULT_EVENT"
    EVIDENCE = "EVIDENCE"


class FreshnessState(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    EXPIRED = "EXPIRED"
    TIMING_INVALID = "TIMING_INVALID"
    UNKNOWN = "UNKNOWN"


class ReplayState(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    ACCEPTABLE = "ACCEPTABLE"
    DUPLICATE = "DUPLICATE"
    OUT_OF_SEQUENCE = "OUT_OF_SEQUENCE"
    REPLAY_SUSPECTED = "REPLAY_SUSPECTED"


class IntegrityState(StrEnum):
    INTEGRITY_VALID = "INTEGRITY_VALID"
    INTEGRITY_DEGRADED = "INTEGRITY_DEGRADED"
    INTEGRITY_FAILED = "INTEGRITY_FAILED"


class AuthState(StrEnum):
    INTEGRITY_VALID = "INTEGRITY_VALID"
    AUTH_UNVERIFIED = "AUTH_UNVERIFIED"
    AUTH_INVALID = "AUTH_INVALID"


class ReviewSignificance(StrEnum):
    ROUTINE = "ROUTINE"
    IMPORTANT = "IMPORTANT"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class FaultLifecycleState(StrEnum):
    DETECTED = "DETECTED"
    SUSPECTED = "SUSPECTED"
    CONFIRMED = "CONFIRMED"
    ISOLATING = "ISOLATING"
    ISOLATED = "ISOLATED"
    MITIGATING = "MITIGATING"
    CONTAINED = "CONTAINED"
    RECOVERING = "RECOVERING"
    CLEARED = "CLEARED"
    LATCHED = "LATCHED"
